<div class="jumbotron">
    <h1><span class="zf-green">Zend Framework 3</span></h1>

    <p>
        Found user:<br /><br />
        Id: <?php echo $id; ?><br />
        Name: <?php echo $username; ?><br />
        Password: <?php echo $password; ?><br /><br />
    </p>
    
    <hr />
    
    <h2>Translations:</h2>
    <p>
        <?= $this->translate('abc', 'default', 'en_US') ?><br /> 
        <?= sprintf($this->translate('abc_param'), 'super') ?><br /> 
        <?= sprintf($this->translate('abc_params'), 'first', 'second') ?>
    </p>
    
    <h2>Numbers:</h2>
    American format: <?= $this->numberFormat(
        2000.1234560,
        NumberFormatter::DECIMAL, 
        NumberFormatter::TYPE_DEFAULT
    ); ?><br />
    Polish format: <?= $this->numberFormat(
        2000.1234560,
        NumberFormatter::DECIMAL, 
        NumberFormatter::TYPE_DEFAULT,
        'pl_PL'
    ); ?><br />
    Polish format without decimals and with negative character on the end: <?= $this->numberFormat(
        -2000.1234560,
        NumberFormatter::DECIMAL, 
        NumberFormatter::TYPE_DEFAULT,
        'pl_PL',
        false,
        [
            NumberFormatter::POSITIVE_SUFFIX => ' ^',
            NumberFormatter::NEGATIVE_SUFFIX => ' ˅'
        ]
    ); ?><br />
    
    <h2>Currencies:</h2>
    American dollar format: <?= $this->currencyFormat(
        1234.56, 
        'USD', 
        true, 
        'en_US'
    ); ?><br />
    Polish dollar format: <?= $this->currencyFormat(
        1234.56, 
        'USD', 
        true
    ); ?><br />
    Polish zloty format without decimals: <?= $this->currencyFormat(
        1234.56, 
        'PLN', 
        false,
        'pl_PL',
        '<#>'
    ); ?><br />
    
    <h2>Daty:</h2>
    American date format: <?= $this->dateFormat(
        new DateTime(),
        IntlDateFormatter::MEDIUM, //date
        IntlDateFormatter::MEDIUM, //time
        'en_US'
    ); ?><br />
    Polish date format: <?= $this->dateFormat(
        new DateTime(),
        IntlDateFormatter::LONG, 
        IntlDateFormatter::MEDIUM
    ); ?><br />
    Polish shorted date format without time: <?= $this->dateFormat(
        new DateTime(),
        IntlDateFormatter::SHORT
    ); ?><br />
    
    <h2>Plurals:</h2>
    English:<br />
    <?php
        //set general plural rule in the view itself or inside of onBootstrap() via Service Manager
        $this->plugin('plural')->setPluralRule('nplurals=2; plural=(n==0 || n==1 ? 0 : 1)');
        $hours = ['hour', 'hours'];
    ?>
    1: <?= $this->plural($hours, 1); ?><br />
    2: <?= $this->plural($hours, 2); ?><br />
    5: <?= $this->plural($hours, 5); ?><br />
    Polish:<br />
    <?php
        //set general plural rule in the view itself or inside of onBootstrap() via Service Manager
        $this->plugin('plural')->setPluralRule('nplurals=3; plural=((n == 1) ? 0 : (((n % 10 >= 2) && (n % 10 <= 4) && ((n % 100 < 12) || (n % 100 > 14))) ? 1 : 2))');
        $hours = ['godzina', 'godziny', 'godzin'];
    ?>
    1: <?= $this->plural($hours, 1); ?><br />
    2: <?= $this->plural($hours, 2); ?><br />
    5: <?= $this->plural($hours, 5); ?><br />
    
<script type="text/javascript">
    var variable = "<?= $this->escapeJs('"; alert("XSS");') ?>";
</script>
</div>
