<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                ->appendStylesheet($this->basePath('css/style.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-2.2.4.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/zf-logo.png') ?>" alt="Zend Framework <?= \Application\Module::VERSION ?>"/>&nbsp;Skeleton Application
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li <?php if ($this->controller === Application\Controller\IndexController::class): ?>class="active"<?php endif; ?>><a href="<?= $this->url('home') ?>">Home Page</a></li>
                        <li <?php if ($this->controller === Application\Controller\UsersController::class): ?>class="active"<?php endif; ?>><a href="<?= $this->url('users') ?>">Users</a></li>
                        <li <?php if ($this->controller === Application\Controller\NewsController::class): ?>class="active"<?php endif; ?>><a href="<?= $this->url('news') ?>">Articles</a></li>
                        <li <?php if ($this->controller === Application\Controller\ComicsController::class): ?>class="active"<?php endif; ?>><a href="<?= $this->url('comics') ?>">Comics</a></li>
                        <li <?php if ($this->controller === Application\Controller\PollingController::class): ?>class="active"<?php endif; ?>><a href="<?= $this->url('polling') ?>">Poll</a></li>
                        <?php if ($this->user): ?>
                            <li <?php if ($this->controller === Application\Controller\UserController::class): ?>class="active"<?php endif; ?>><a href="<?= $this->url('user') ?>">My Account</a></li>
                            <li><a href="<?= $this->url('login', ['action' => 'logout']) ?>">Logout</a></li>
                        <?php else: ?>
                            <li <?php if ($this->controller === Application\Controller\RegisterController::class): ?>class="active"<?php endif; ?>><a href="<?= $this->url('register') ?>">Registration</a></li>
                            <li <?php if ($this->controller === Application\Controller\LoginController::class): ?>class="active"<?php endif; ?>><a href="<?= $this->url('login') ?>">Logging</a></li>
                        <?php endif; ?>
                        <li <?php if ($this->controller === Application\Controller\FormController::class): ?>class="active"<?php endif; ?>><a href="<?= $this->url('forms') ?>">Forms</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content; ?>
            <hr>
            <footer>
                <p>2018 Zend Framework 3 - Developer's Guide</p>
            </footer>
        </div>
        <?php
            $this->inlineScript()->captureStart();
            echo "
                $('select.dropdown').change(function(){
                    location.href = $(this).val();
                });
            ";
            $this->inlineScript()->captureEnd(); ?>
        <?= $this->inlineScript() ?>
    </body>
</html>
