
<section class="page-content">
    <div class="container">
        <!-- registration -->
        <div class="formContainer">
           <script type="text/javascript" src="<?= $baseUrl ?>public/scripts/jquery.captchaRefresh.js"></script>
           
           <div class="row">
                <div class="col-md-6">
                    <div class="box">
                        <h3><span class="glyphicon glyphicon-user"></span> Registration</h3>
                        <?= $messages ?>
                        <?php
                            $userForm->prepare();
                            
                            echo $this->form()->openTag($userForm);
                            echo $this->formRow($userForm->get('username'));
                            echo $this->formRow($userForm->get('password'));
                            echo $this->formHidden($userForm->get('csrf'));
                            
                            echo $this->formSubmit($userForm->get('submit'));
                            echo $this->form()->closeTag();
                        ?>
                    </div>
                </div>
                <div class="col-md-6">
                </div>
            </div>

        </div>
    </div>
</section>       