<?= $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?= $this->headTitle(isset($title) ? $title : 'Admin Panel - Zend Framework 3')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('description', isset($description) ? $description : 'Default description')
        ->appendName('keywords', isset($keywords) ? $keywords : 'Default keywords')
        ->appendName('viewport', 'width=device-width, initial-scale=1.0') 
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge') 
    ?>

    <!-- Le styles -->
    <?= $this->headLink()
        ->prependStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css')
        ->prependStylesheet($this->basePath('css/style.css'))?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js')
        ->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js')
        ->prependFile('https://oss.maxcdn.com/respond/1.4.2/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile('https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ->appendFile('//cdn.ckeditor.com/4.6.2/full/ckeditor.js')
    ?>

  </head>

  <body style="padding-top: 70px;">

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?= $this->url('admin') ?>">Admin Panel</a>
                </div>
                <div class="collapse navbar-collapse">
                    <?= $this->navigation('admin_navigation')
                            ->menu()
                            ->setUlClass('nav navbar-nav')
                            ->setMaxDepth(0)
                            ->setRenderInvisible(false)?>
                </div><!--/.nav-collapse -->
            </div>
        </nav>

    <div class="container">
        <?php
            $flash = $this->flashMessenger();
            $flash->setMessageOpenFormat('<div%s>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                &times;
            </button>
            <div>')->setMessageCloseString('</div></div>');

            $flash->clearMessagesFromContainer(); 
            echo $flash->renderCurrent('error', ['alert', 'alert-dismissable', 'alert-danger']);
            echo $flash->renderCurrent('warning', ['alert', 'alert-dismissable', 'alert-warning']);
            echo $flash->renderCurrent('info', ['alert', 'alert-dismissable', 'alert-info']);
            echo $flash->renderCurrent('default', ['alert', 'alert-dismissable', 'alert-warning']);
            echo $flash->renderCurrent('success', ['alert', 'alert-dismissable', 'alert-success']);
           
        ?>
        <div class="row">
            <?= $this->content ?>
        </div>

      <hr>

      <?= $this->partial('application/_shared/footer.phtml'); ?>

    </div> <!-- /container -->

  <?= $this->inlineScript() ?>
  </body>
</html>